#To save your changes, copy your custom theme into the clipboard and paste it into the [theme] section of your .streamlit/config.toml file.
[theme]
primaryColor="#0bfbse"
backgroundColor="#402c90"
secondaryBackgroundColor="#172303"
textColor="#e9e8f3"
